### ISSUE TITLE
As of an update to Intellij 5/18/2020, this is no longer working.

### ISSUE THREAD

**Issue by geektechniquestudios** [alexatiks/jetbrains-reset-trial-evaluation-mac#6]
I believe there is something preventing this code from working in version 2020.1.1

**Comment by alexatiks** [comment]
@geektechniquestudios Can't reproduce, have you tried to reboot after running the script?

**Comment by geektechniquestudios** [comment]
I did try restarting before and after running the script. I've determined through using a different machine that the issue I experienced was local and not the result of a change in IntelliJ. I apologize for the false flag; thanks for taking the time to respond.
