### ISSUE TITLE
Rider 2020 support

### ISSUE THREAD

**Issue by OzaS** [alexatiks/jetbrains-reset-trial-evaluation-mac#8]
Sadly, Rider 2020.* is not supported. I have tried to add Rider to the list, and it works partly - evaluation has been removed, but on the first start the new 30-day trial is gone instantly. Maybe one of the locations is missed. Tried to remove the folder completely - nothing has worked

<img width="1121" alt="Screenshot 2020-05-27 at 02 35 06" src="https://user-images.githubusercontent.com/8199582/82960322-dd178780-9fc2-11ea-9ca6-49365e9a6c07.png">

**Comment by alexatiks** [comment]
@OzaS Added support for Rider. 
Have you reboot mac os after running the script? Seems it's cached.

**Comment by OzaS** [comment]
I have managed to find the reason - we are deleting the system .plist files, but macOS won't recreate them before the system restart, so what we need to do is to restart the OS
